### ISSUE TITLE
Endpoint keeps returning 500

### ISSUE THREAD

**Issue by mcfriend99** [Allen-Taylor/pump_fun_py#3]
The endpoint: https://frontend-api.pump.fun/ now returns 500 Internal Server error on every request.

**Comment by Allen-Taylor** [comment]
![image](https://github.com/Allen-Taylor/pump_fun_py/assets/98119917/788deb26-d48f-48f5-bdf1-42dbb34ca651)

works for me. maybe you're getting rate limited?
