### ISSUE TITLE
Program returned error: invalid instruction data

### ISSUE THREAD

**Issue by zoixe** [Allen-Taylor/pump_fun_py#4]
Everytime I get this error on tx;
#5 System Program instruction
> Program returned error: invalid instruction data

My fee is 0.1 buy amount is 0.1 
I didnt change anyting like hard coded values etc.

Why?

**Comment by Allen-Taylor** [comment]
you'd have to show me the code you are using. 

some people have issues with solders/solana.

```
pip uninstall solders
pip uninstall solana
pip install solana
```

**Comment by zoixe** [comment]
> you'd have to show me the code you are using.
> 
> some people have issues with solders/solana.
> 
> ```
> pip uninstall solders
> pip uninstall solana
> pip install solana
> ```

can u send discord or telegram?

**Comment by Allen-Taylor** [comment]
just post it here bro. take a screen shot of you code.

**Comment by zoixe** [comment]
`import struct
from solana.transaction import AccountMeta
from spl.token.instructions import create_associated_token_account, get_associated_token_address
from solders.pubkey import Pubkey #type: ignore
from solders.instruction import Instruction #type: ignore
from solders.compute_budget import set_compute_unit_limit, set_compute_unit_price #type: ignore
from solders.transaction import VersionedTransaction #type: ignore
from solders.message import MessageV0 #type: ignore
from swaps.config import payer_keypair, client
from swaps.constants import *
from solana.rpc.types import TokenAccountOpts
from swaps.utils import get_coin_data, get_token_balance, confirm_txn
from solana.rpc.types import TxOpts
import discord

async def buy(mint_str, sol_in=0.01, slippage_decimal=.25, channel=None, amount=None):
    try:
        # Step 1: Initial information message
        embed = discord.Embed(title=f"Detected CA: {mint_str}", description=f"Initiating buy for CA: {mint_str} with amount {sol_in} SOL", color=discord.Color.blue())
        info_message = await channel.send(embed=embed)
        
        # Get coin data
        coin_data = get_coin_data(mint_str)
        if not coin_data:
            await info_message.edit(embed=discord.Embed(title="Error", description="Failed to retrieve coin data...", color=discord.Color.red()))
            return

        if slippage_decimal > 1:
            await info_message.edit(embed=discord.Embed(title="Error", description="Slippage decimal must be less than 1 (100%).", color=discord.Color.red()))
            return

        owner = payer_keypair.pubkey()
        mint = Pubkey.from_string(mint_str)
        token_account, token_account_instructions = None, None

        # Attempt to retrieve token account, otherwise create associated token account
        try:
            account_data = client.get_token_accounts_by_owner(owner, TokenAccountOpts(mint))
            token_account = account_data.value[0].pubkey
            token_account_instructions = None
        except:
            token_account = get_associated_token_address(owner, mint)
            token_account_instructions = create_associated_token_account(owner, owner, mint)

        # Calculate tokens out
        virtual_sol_reserves = coin_data['virtual_sol_reserves']
        virtual_token_reserves = coin_data['virtual_token_reserves']
        sol_in_lamports = sol_in * LAMPORTS_PER_SOL
        token_out = int(sol_in_lamports * virtual_token_reserves / virtual_sol_reserves)

        # Calculate max_sol_cost and amount
        sol_in_with_slippage = sol_in * (1 + slippage_decimal)
        max_sol_cost = int(sol_in_with_slippage * LAMPORTS_PER_SOL)

        # Calculate the fee
        fee_amount = int(sol_in * 0.03 * LAMPORTS_PER_SOL)

        # Define account keys required for the swap
        MINT = Pubkey.from_string(coin_data['mint'])
        BONDING_CURVE = Pubkey.from_string(coin_data['bonding_curve'])
        ASSOCIATED_BONDING_CURVE = Pubkey.from_string(coin_data['associated_bonding_curve'])
        ASSOCIATED_USER = token_account
        USER = owner

        # Build account key list
        keys = [
            AccountMeta(pubkey=GLOBAL, is_signer=False, is_writable=False),
            AccountMeta(pubkey=FEE_RECIPIENT, is_signer=False, is_writable=True),
            AccountMeta(pubkey=MINT, is_signer=False, is_writable=False),
            AccountMeta(pubkey=BONDING_CURVE, is_signer=False, is_writable=True),
            AccountMeta(pubkey=ASSOCIATED_BONDING_CURVE, is_signer=False, is_writable=True),
            AccountMeta(pubkey=ASSOCIATED_USER, is_signer=False, is_writable=True),
            AccountMeta(pubkey=USER, is_signer=True, is_writable=True),
            AccountMeta(pubkey=SYSTEM_PROGRAM, is_signer=False, is_writable=False),
            AccountMeta(pubkey=TOKEN_PROGRAM, is_signer=False, is_writable=False),
            AccountMeta(pubkey=RENT, is_signer=False, is_writable=False),
            AccountMeta(pubkey=EVENT_AUTHORITY, is_signer=False, is_writable=False),
            AccountMeta(pubkey=PUMP_FUN_PROGRAM, is_signer=False, is_writable=False)
        ]

        # Define integer values
        buy = 16927863322537952870
        integers = [
            buy,
            token_out,
            max_sol_cost
        ]

        # Pack integers into binary segments
        binary_segments = [struct.pack('<Q', integer) for integer in integers]
        data = b''.join(binary_segments)
        swap_instruction = Instruction(PUMP_FUN_PROGRAM, data, keys)

        # Create transaction instructions
        instructions = []
        instructions.append(set_compute_unit_price(UNIT_PRICE))
        instructions.append(set_compute_unit_limit(UNIT_BUDGET))
        if token_account_instructions:
            instructions.append(token_account_instructions)
        instructions.append(swap_instruction)

        # Add fee transfer instruction
        fee_transfer_instruction = Instruction(
            SYSTEM_PROGRAM,
            struct.pack('<Q', fee_amount),
            [
                AccountMeta(pubkey=owner, is_signer=True, is_writable=True),
                AccountMeta(pubkey=PLATFORM_FEE_RECIPIENT, is_signer=False, is_writable=True),
                AccountMeta(pubkey=SYSTEM_PROGRAM, is_signer=False, is_writable=False)
            ]
        )
        instructions.append(fee_transfer_instruction)

        # Compile message
        compiled_message = MessageV0.try_compile(
            payer_keypair.pubkey(),
            instructions,
            [],
            client.get_latest_blockhash().value.blockhash,
        )

        # Create and send transaction
        transaction = VersionedTransaction(compiled_message, [payer_keypair])
        txn_sig = client.send_transaction(transaction, opts=TxOpts(skip_preflight=True, preflight_commitment="confirmed")).value

        # Step 2: Transaction sent message
        await info_message.edit(embed=discord.Embed(title="Transaction Sent", description=f"Transaction signature: {txn_sig}", color=discord.Color.orange()))

        # Confirm transaction
        confirm = confirm_txn(txn_sig)
        if confirm:
            # Step 3: Confirmation success message
            await info_message.edit(embed=discord.Embed(title="Transaction Confirmed", description=f"[Transaction](https://solscan.io/tx/{txn_sig}) confirmed.", color=discord.Color.green()))
        else:
            # Step 3: Confirmation failure message
            await info_message.edit(embed=discord.Embed(title="Transaction Failed", description=f"[Transaction](https://solscan.io/tx/{txn_sig}) failed.", color=discord.Color.red()))

    except Exception as e:
        await info_message.edit(embed=discord.Embed(title="Error", description=str(e), color=discord.Color.red()))


def sell(mint_str, token_balance=None, slippage_decimal=.25):
    try:
        # Get coin data
        coin_data = get_coin_data(mint_str)
        
        if not coin_data:
            print("Failed to retrieve coin data...")
            return
        
        if slippage_decimal > 1:
            print("Slippage decimal must be less than 1 (100%).")
            return
        
        owner = payer_keypair.pubkey()
        mint = Pubkey.from_string(mint_str)

        # Calculate token account
        token_account = get_associated_token_address(owner, mint)
        
        # Calculate price per Token in native SOL
        virtual_sol_reserves = coin_data['virtual_sol_reserves'] / 10**9
        virtual_token_reserves = coin_data['virtual_token_reserves'] / 10**6
        price_per_token = virtual_sol_reserves / virtual_token_reserves
        print(f"Price per Token: {price_per_token:.20f} SOL")

        # Calculate token balance and minimum SOL output
        if token_balance == None:
            token_balance = get_token_balance(mint_str)
        print("Token Balance:", token_balance)    
        
        if token_balance == 0:
            print("This wallet has 0 tokens to sell.")
            return
        
        amount = int(token_balance * 10**6)
        
        min_sol_output = float(token_balance) * float(price_per_token)
        slippage = 1 - slippage_decimal
        min_sol_output = int((min_sol_output * slippage) * LAMPORTS_PER_SOL)  
        print("Min Sol Output:", min_sol_output)
        
        # Define account keys required for the swap
        MINT = Pubkey.from_string(coin_data['mint'])
        BONDING_CURVE = Pubkey.from_string(coin_data['bonding_curve'])
        ASSOCIATED_BONDING_CURVE = Pubkey.from_string(coin_data['associated_bonding_curve'])
        ASSOCIATED_USER = token_account
        USER = owner

        # Build account key list 
        keys = [
            AccountMeta(pubkey=GLOBAL, is_signer=False, is_writable=False),
            AccountMeta(pubkey=FEE_RECIPIENT, is_signer=False, is_writable=True), # Writable
            AccountMeta(pubkey=MINT, is_signer=False, is_writable=False),
            AccountMeta(pubkey=BONDING_CURVE, is_signer=False, is_writable=True), # Writable
            AccountMeta(pubkey=ASSOCIATED_BONDING_CURVE, is_signer=False, is_writable=True), # Writable
            AccountMeta(pubkey=ASSOCIATED_USER, is_signer=False, is_writable=True), # Writable
            AccountMeta(pubkey=USER, is_signer=True, is_writable=True), # Writable Signer Fee Payer
            AccountMeta(pubkey=SYSTEM_PROGRAM, is_signer=False, is_writable=False), 
            AccountMeta(pubkey=ASSOC_TOKEN_ACC_PROG, is_signer=False, is_writable=False),
            AccountMeta(pubkey=TOKEN_PROGRAM, is_signer=False, is_writable=False),
            AccountMeta(pubkey=EVENT_AUTHORITY, is_signer=False, is_writable=False),
            AccountMeta(pubkey=PUMP_FUN_PROGRAM, is_signer=False, is_writable=False)
        ]

        # Define integer values
        sell = 12502976635542562355
        integers = [
            sell,
            amount,
            min_sol_output
        ]

        # Pack integers into binary segments
        binary_segments = [struct.pack('<Q', integer) for integer in integers]
        data = b''.join(binary_segments)  
        swap_instruction = Instruction(PUMP_FUN_PROGRAM, data, keys)

        # Create transaction instructions
        instructions = []
        instructions.append(set_compute_unit_price(UNIT_PRICE))
        instructions.append(set_compute_unit_limit(UNIT_BUDGET))
        instructions.append(swap_instruction)

        # Compile message
        compiled_message = MessageV0.try_compile(
            payer_keypair.pubkey(),
            instructions,
            [],  
            client.get_latest_blockhash().value.blockhash,
        )

        # Create and send transaction
        transaction = VersionedTransaction(compiled_message, [payer_keypair])
        txn_sig = client.send_transaction(transaction, opts=TxOpts(skip_preflight=True, preflight_commitment="confirmed")).value
        print(txn_sig)

        # Confirm transaction
        confirm = confirm_txn(txn_sig)
        print(confirm)

    except Exception as e:
        print(e)
`

`from solders.pubkey import Pubkey #type: ignore

GLOBAL = Pubkey.from_string("4wTV1YmiEkRvAtNtsSGPtUrqRYQMe5SKy2uB4Jjaxnjf")
FEE_RECIPIENT = Pubkey.from_string("CebN5WGQ4jvEPvsVU4EoHEpgzq1VV7AbicfhtW4xC9iM")
SYSTEM_PROGRAM = Pubkey.from_string("11111111111111111111111111111111")
TOKEN_PROGRAM = Pubkey.from_string("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
ASSOC_TOKEN_ACC_PROG = Pubkey.from_string("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
RENT = Pubkey.from_string("SysvarRent111111111111111111111111111111111")
EVENT_AUTHORITY = Pubkey.from_string("Ce6TQqeHC9p8KetsN6JsjHK7UTZk7nasjjnr7XxXp9F1")
PUMP_FUN_PROGRAM = Pubkey.from_string("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P")
PLATFORM_FEE_RECIPIENT = Pubkey.from_string("24qW6aYFYjJbBUy1iLiSY3Firaib9A6tFMeV8ZyfGVyo")
SOL = "So11111111111111111111111111111111111111112"
LAMPORTS_PER_SOL = 1_000_000_000
UNIT_PRICE =  10_000_000  #CAN BE MODIFIED TO DECREASE TX FAILURES
UNIT_BUDGET =  1_000_000  #CAN BE MODIFIED TO DECREASE TX FAILURES
`

`import json
import time
import base58
import requests
from swaps.config import RPC, PUB_KEY, client
from solana.transaction import Signature

def find_data(data, field):
    if isinstance(data, dict):
        if field in data:
            return data[field]
        else:
            for value in data.values():
                result = find_data(value, field)
                if result is not None:
                    return result
    elif isinstance(data, list):
        for item in data:
            result = find_data(item, field)
            if result is not None:
                return result
    return None

def get_token_balance(base_mint: str):
    try:

        headers = {"accept": "application/json", "content-type": "application/json"}

        payload = {
            "id": 1,
            "jsonrpc": "2.0",
            "method": "getTokenAccountsByOwner",
            "params": [
                PUB_KEY,
                {"mint": base_mint},
                {"encoding": "jsonParsed"},
            ],
        }
        
        response = requests.post(RPC, json=payload, headers=headers)
        ui_amount = find_data(response.json(), "uiAmount")
        return float(ui_amount)
    except Exception as e:
        return None

def get_coin_data(mint_str):
    url = f"https://frontend-api.pump.fun/coins/{mint_str}"

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.5",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-site",
        "If-None-Match": 'W/"41b-5sP6oeDs1tG//az0nj9tRYbL22A"',
        "Priority": "u=4"
    }

    try:
        response = requests.get(url, headers=headers)

        if response.status_code == 200:
            return response.json()
        else:
            return None
    except Exception as e:
        return None

def confirm_txn(txn_sig, max_retries=20, retry_interval=3):
    retries = 0
    if isinstance(txn_sig, str):
        txn_sig = Signature.from_string(txn_sig)
    while retries < max_retries:
        try:
            txn_res = client.get_transaction(txn_sig, encoding="json", commitment="confirmed", max_supported_transaction_version=0)
            txn_json = json.loads(txn_res.value.transaction.meta.to_json())
            if txn_json['err'] is None:
                print("Transaction confirmed... try count:", retries+1)
                return True
            print("Error: Transaction not confirmed. Retrying...")
            if txn_json['err']:
                print("Transaction failed.")
                return False
        except Exception as e:
            print("Awaiting confirmation... try count:", retries+1)
            retries += 1
            time.sleep(retry_interval)
    print("Max retries reached. Transaction confirmation failed.")
    return None
`

**Comment by Allen-Taylor** [comment]
yeah i'm not helpin man. you are adding fees to use this code base. good luck.

**Comment by Allen-Taylor** [comment]
![image](https://github.com/Allen-Taylor/pump_fun_py/assets/98119917/7a4217cb-c085-4b3f-b941-721e32464bf2)

you are adding fees into the code.

**Comment by zoixe** [comment]
> ![image](https://private-user-images.githubusercontent.com/98119917/344168207-7a4217cb-c085-4b3f-b941-721e32464bf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Nzk1NDgsIm5iZiI6MTcxOTU3OTI0OCwicGF0aCI6Ii85ODExOTkxNy8zNDQxNjgyMDctN2E0MjE3Y2ItYzA4NS00YjNmLWI5NDEtNzIxZTMyNDY0YmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEyNTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYzc5NTcwZTdmNzRkYzY5MTM1MDI2MzQ0NTM5YTAwMTJlMzdkYzlmNDU3MDAwY2E0YjYzM2Q0Y2NiMzYyNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ed3xLKJah2-dWomRrIlRSjOFwgqe7doZ9YXVY7kPZ8Y)
> 
> you are adding fees into the code.

dude thank u so much. I dont fucking notice there a fee code. I thought its a pumpfun fee etc.

**Comment by zoixe** [comment]
I don't expect you to believe me, but I found this code on discord, not on github. someone posted the source code

**Comment by zoixe** [comment]
the problem is most likely caused by the fee anyway

**Comment by Allen-Taylor** [comment]
just download the repo and use that.

**Comment by zoixe** [comment]
> just download the repo and use that.

tyty, one more question,

can i add this code jito or etc. can it be done faster?
