### ISSUE TITLE
How do I add a gas fee?

### ISSUE THREAD

**Issue by IsoyaYuki** [Allen-Taylor/pump_fun_py#5]
Looking for the code it doesn't appear to have a gas fee

**Comment by Allen-Taylor** [comment]
look in the constants.py file. 

UNIT_PRICE =  10_000_000
UNIT_BUDGET =  100_000

Modify increase the unit price to increase the priority fee.

**Comment by IsoyaYuki** [comment]
thank you So again, developers, how do you set the priority fee for pumps?

**Comment by IsoyaYuki** [comment]
How to set up Pump.fun Fee Account?

**Comment by Allen-Taylor** [comment]
I don't know what you mean. Sorry.

**Comment by IsoyaYuki** [comment]
![12b03193dda17b4644c9bfa581ded34](https://github.com/user-attachments/assets/9d3bbd63-a6b7-48fc-84c4-a93967c3a391)
this cost

**Comment by Allen-Taylor** [comment]
It's a fixed fee automatically calculated by the pump fun program itself. 

Are you having issues with the code?

**Comment by IsoyaYuki** [comment]
The code is fine, very good code, thanks for the answer!
