### ISSUE TITLE
sol balance transerfer to （System Program）11111111111111111111111111111111

### ISSUE THREAD

**Issue by Lance-soon** [Allen-Taylor/pump_fun_py#7]
when I test the code use my sol wallet, but here it run not as I hope, when it match "Max retries reached. Transaction confirmation failed.
", i found all of my sol balance transerfer to （System Program）11111111111111111111111111111111.

is this pragram work correctly ?

**Comment by Allen-Taylor** [comment]
You obviously got scammed. You didn't use my repo though.
